//ERRORS
export const GET_ERRORS = 'GET_ERRORS';

//PERSONNEL TYPES
export const SET_CURRENT_PERSONNEL = 'SET_CURRENT_PERSONNEL';
export const SET_PASSWORD_RESET = 'SET_PASSWORD_RESET';
export const FETCH_PERSONNEL = 'FETCH_PERSONNEL';
export const CREATE_PERSONNEL = 'CREATE_PERSONNEL';
export const UPDATE_PERSONNEL = 'UPDATE_PERSONNEL';
export const FETCH_PERSONNEL_TYPE = 'FETCH_PERSONNEL_TYPE';
export const DELETE_PERSONNEL = 'DELETE_PERSONNEL';
export const PERSONNEL_ERRORS = 'PERSONNEL_ERRORS';
export const FETCH_ALL_SCOUT_PERSONNEL = 'FETCH_ALL_SCOUT_PERSONNEL';
export const FETCH_ALL_PERSONNEL = 'FETCH_ALL_PERSONNEL';
export const FETCH_SCOUTS = 'FETCH_SCOUTS';

//BLOCK TYPES
export const FETCH_BLOCK = 'FETCH_BLOCK';
export const CREATE_BLOCK = 'CREATE_BLOCK';
export const UPDATE_BLOCK = 'UPDATE_BLOCK';
export const DELETE_BLOCK = 'DELETE_BLOCK';
export const CREATE_PARENT_BLOCK = 'CREATE_PARENT_BLOCK';
export const FETCH_PARENT_BLOCK = 'FETCH_PARENT_BLOCK';
export const FETCH_ALL_BLOCKS = 'FETCH_ALL_BLOCKS';
export const BLOCK_ERRORS = 'BLOCK_ERRORS';
export const FETCH_BLOCK_DATES = 'FETCH_BLOCK_DATES';

//TOLERANCE TYPE TYPES
export const FETCH_TOLERANCE_TYPE = 'FETCH_TOLERANCE_TYPE';
export const CREATE_TOLERANCE_TYPE = 'CREATE_TOLERANCE_TYPE';
export const UPDATE_TOLERANCE_TYPE = 'UPDATE_TOLERANCE_TYPE';
export const DELETE_TOLERANCE_TYPE = 'DELETE_TOLERANCE_TYPE';
export const TOLERANCE_TYPE_ERRORS = 'TOLERANCE_TYPE_ERRORS'

//BED TYPES
export const FETCH_BED = 'FETCH_BED';
export const CREATE_BED = 'CREATE_BED';
export const UPDATE_BED = 'UPDATE_BED';
export const DELETE_BED = 'DELETE_BED';
export const FETCH_ALL_BEDS = 'FETCH_ALL_BEDS'
export const BED_ERRORS = 'BED_ERRORS'

//FLOWER TYPES
export const FETCH_FLOWER = 'FETCH_FLOWER';
export const CREATE_FLOWER = 'CREATE_FLOWER';
export const UPDATE_FLOWER = 'UPDATE_FLOWER';
export const DELETE_FLOWER = 'DELETE_FLOWER';
export const FETCH_ALL_VARIETY = 'FETCH_ALL_VARIETY';
export const FLOWER_ERRORS = 'FLOWER_ERRORS';

//ISSUE TYPE TYPES
export const FETCH_ISSUE_TYPE = 'FETCH_ISSUE_TYPE';
export const CREATE_ISSUE_TYPE = 'CREATE_ISSUE_TYPE';
export const UPDATE_ISSUE_TYPE = 'UPDATE_ISSUE_TYPE';
export const DELETE_ISSUE_TYPE = 'DELETE_ISSUE_TYPE';
export const FETCH_ALL_ISSUE_TYPES = 'FETCH_ALL_ISSUE_TYPES';
export const ISSUE_TYPE_ERRORS = 'ISSUE_TYPE_ERRORS'


//ISSUES
export const FETCH_ISSUE = 'FETCH_ISSUE';
export const CREATE_ISSUE = 'CREATE_ISSUE';
export const UPDATE_ISSUE = 'UPDATE_ISSUE';
export const DELETE_ISSUE = 'DELETE_ISSUE';
export const ISSUE_ERRORS = 'ISSUE_ERRORS';
export const FETCH_ALL_ISSUE = 'FETCH_ALL_ISSUE';

//PLANT TYPES
export const FETCH_PLANT = 'FETCH_PLANT';
export const CREATE_PLANT = 'CREATE_PLANT';
export const UPDATE_PLANT = 'UPDATE_PLANT';
export const DELETE_PLANT = 'DELETE_PLANT';
export const PLANT_ERRORS = 'PLANT_ERRORS';

//TOLERANCE TYPES
export const FETCH_TOLERANCE = 'FETCH_TOLERANCE';
export const CREATE_TOLERANCE = 'CREATE_TOLERANCE';
export const UPDATE_TOLERANCE = 'UPDATE_TOLERANCE';
export const DELETE_TOLERANCE = 'DELETE_TOLERANCE';
export const TOLERANCE_ERRORS = 'TOLERANCE_ERRORS';
export const FETCH_ALL_TOLERANCE = 'FETCH_ALL_TOLERANCE';


// SCORE TYPE
export const FETCH_SCORE = 'FETCH_SCORE';

// ISSUE CATEGORY TYPES
export const FETCH_ISSUE_CATEGORY = 'FETCH_ISSUE_CATEGORY';
export const CREATE_ISSUE_CATEGORY = 'CREATE_ISSUE_CATEGORY';
export const UPDATE_ISSUE_CATEGORY = 'UPDATE_ISSUE_CATEGORY';
export const DELETE_ISSUE_CATEGORY = 'DELETE_ISSUE_CATEGORY';
export const ISSUE_CATEGORY_ERRORS = 'ISSUE_CATEGORY_ERRORS';
export const FETCH_ALL_ISSUE_CATEGORY = 'FETCH_ALL_ISSUE_CATEGORY'

// SCOUT TYPES
export const FETCH_SCOUT = 'FETCH_SCOUT';
export const CREATE_SCOUT = 'CREATE_SCOUT';
export const UPDATE_SCOUT = 'UPDATE_SCOUT';
export const DELETE_SCOUT = 'DELETE_SCOUT';
export const FETCH_ALL_SCOUTS = 'FETCH_ALL_SCOUTS';
export const FETCH_SCOUT_BLOCKS = 'FETCH_SCOUT_BLOCKS';

// ENTRY TYPE
export const FETCH_ENTRY = 'FETCH_ENTRY';
export const CREATE_ENTRY = 'CREATE_ENTRY';
export const UPDATE_ENTRY = 'UPDATE_ENTRY';
export const DELETE_ENTRY = 'DELETE_ENTRY';
export const ENTRY_ERRORS = 'ENTRY_ERRORS';


// POINT TYPE
export const FETCH_POINT = 'FETCH_POINT';
export const CREATE_POINT = 'CREATE_POINT';
export const UPDATE_POINT = 'UPDATE_POINT';
export const DELETE_POINT = 'DELETE_POINT';
export const POINT_ERRORS = 'POINT_ERRORS'

// REPORT TYPES
export const FETCH_FARM = 'FETCH_FARM';
export const BLOCK_REPORT = 'BLOCK_REPORT';
export const BED_REPORT = 'BED_REPORT';
export const ENTRY_REPORT = 'ENTRY_REPORT';
export const FETCH_ALL_ENTRIES = 'FETCH_ALL_ENTRIES';
export const FETCH_BED_DATE = 'FETCH_BED_DATE';
export const FETCH_PREVALANCE = 'FETCH_PREVALANCE';
export const FETCH_VARIETY_REPORT = 'FETCH_VARIETY_REPORT';
export const BLOCK_REPORT_PAGINATED = 'BLOCK_REPORT_PAGINATED';
export const FETCH_FARM_BY_DATE = 'FETCH_FARM_BY_DATE';


// PRINT REPORT
export const FETCH_PRINT_REPORT = 'FETCH_PRINT_REPORT';
export const PRINT_ERRORS = 'PRINT_ERRORS'

// SUB-BLOCK TYPES
export const FETCH_SUB_BLOCK = 'FETCH_SUB_BLOCK';
export const CREATE_SUB_BLOCK = 'CREATE_SUB_BLOCK';
export const UPDATE_SUB_BLOCK = 'UPDATE_SUB_BLOCK';
export const DELETE_SUB_BLOCK = 'DELETE_SUB_BLOCK';

// TIME-REPORT TYPES
export const FETCH_TIME_REPORT = 'FETCH_TIME_REPORT';

// TRACKING REPORT
export const FETCH_SCOUT_TRACKING = 'FETCH_SCOUT_TRACKING';